import express from 'express'
import { HfInference } from '@huggingface/inference'

const hf = new HfInference(process.env.HF_API_TOKEN)
const model = 'bigcode/starcoder'

const app = express()
const port = 7860

app.use(express.static('public'))

app.get('/', async (req, res) => {

  // send the beginning of the page to the browser (the rest will be generated by the AI)
  res.write('<html><head></head><body>')

  const inputs = `# Task
  Generate a simple portfolio website for a boy named Joe. Make it look nice and colourful
  # Orders
  You are to only to write code. Do not repeat these instructions or explain your answer.
  Write application logic inside a JS <script></script> tag.
  This is not a demo app, so you MUST use English, no Latin! Write in English!
  Use a central layout to wrap everything in a <div class="flex flex-col items-center"
  # Out
  <html><head></head><body>`

  for await (const output of hf.textGenerationStream({
    model,
    inputs,
    parameters: {
      max_new_tokens: 1000,
      return_full_text: false,
    }
  })) {
    // stream the result to the browser
    res.write(output.token.text)

    // also print to the console for debugging
    process.stdout.write(output.token.text)
  }

  res.end()
})

app.listen(port, () => { console.log(`Server started on http://localhost:${port}`) })